### ISSUE TITLE
测试时提示文件找不到

### ISSUE THREAD

**Issue by caojiabin2012** [chuanhaisoft/ChuanHaiShop-php-yaf#1]
1.自己搭建测试时提示文件找不到，应该没上传吧，如图：
![image](https://user-images.githubusercontent.com/12596466/30965201-1cdd474e-a41a-11e7-85a2-7fe1d40ce458.png)

2.这样的地址：http://www.chuanhaisoft.com/pro_list/0_0_0_0_0_1.html 总是不能正常调整，如果方便的话，可以贴下nginx的配置吗？

**Comment by chuanhaisoft** [comment]
上传了
更新 css 和 图片 文件夹

nginx的配置参考：

server {
  listen ****;
  server_name  domain.com;
  root   document_root;
  index  index.php index.html index.htm;

  if (!-e $request_filename) {
    rewrite ^/(.*)  /index.php/$1 last;
  }
}
